### ISSUE TITLE
Not able to run the file

### ISSUE THREAD

**Issue by SXV357** [aneagoie/pokedex#6]
When I grab the files using sys.argv[1] and sys.argv[2], how am I supposed to enter them into the terminal? I tried using the short path that was used in the video(Pokedex/ new/) but since I'm on windows and my file name is Images, I said the file name followed by Images\ new\ but it gives me an error saying that the file wasn't found for some reason. I even tried specifuying the entire path for the folder but I'm just confused as to how to do the same for 2 of them like would I have to specify it for the 1st folder followed by a space and then the 2nd folder or what mistake am I making?

**Comment by Rajith-07** [comment]
you have to mention "Images\ new\" in your case in the terminal after the pyfile

**Comment by amarsanthosh** [comment]
> you have to mention "Images\ new" in your case in the terminal after the pyfile

already tried this but not working

**Comment by amarsanthosh** [comment]
> When I grab the files using sys.argv[1] and sys.argv[2], how am I supposed to enter them into the terminal? I tried using the short path that was used in the video(Pokedex/ new/) but since I'm on windows and my file name is Images, I said the file name followed by Images\ new\ but it gives me an error saying that the file wasn't found for some reason. I even tried specifuying the entire path for the folder but I'm just confused as to how to do the same for 2 of them like would I have to specify it for the 1st folder followed by a space and then the 2nd folder or what mistake am I making?

same problem for me.............

**Comment by Leo-project-A** [comment]
i had this problem as well..
i just used the full path each time. and than added to it the folder of the images
```
import os
# the full path to the directory:  C:\Users\username\....
current_dir = os.path.dirname(__file__) + "\\"
# sys.argv[1] would be 'Pokedex\'
source = sys.argv[1] 
# the path that needed for open() for each image_name in the folder
full_path = current_dir + source + @image_name
```
